In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('flightdata.csv')

In [3]:
dataset

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK UNIQUE_CARRIER  \
0      2016        1      1             1            5             DL   
1      2016        1      1             1            5             DL   
2      2016        1      1             1            5             DL   
3      2016        1      1             1            5             DL   
4      2016        1      1             1            5             DL   
...     ...      ...    ...           ...          ...            ...   
11226  2016        4     12            30            5             DL   
11227  2016        4     12            30            5             DL   
11228  2016        4     12            30            5             DL   
11229  2016        4     12            30            5             DL   
11230  2016        4     12            30            5             DL   

      TAIL_NUM  FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  ...  CRS_ARR_TIME ARR_TIME  \
0       N836DN    1399              10397    ATL  ...          2143   2102.0   
1       N964DN    1476              11433    DTW  ...          1435   1439.0   
2       N813DN    1597              10397    ATL  ...          1215   1142.0   
3       N587NW    1768              14747    SEA  ...          1335   1345.0   
4       N836DN    1823              14747    SEA  ...           607    615.0   
...        ...     ...                ...    ...  ...           ...      ...   
11226   N940DL    1715              11433    DTW  ...          1223   1148.0   
11227   N836DN    1770              14747    SEA  ...          2046   2100.0   
11228   N583NW    1823              11433    DTW  ...          2210   2154.0   
11229   N554NW    1901              10397    ATL  ...          1806   1801.0   
11230   N843DN    2005              10397    ATL  ...           925    913.0   

       ARR_DELAY  ARR_DEL15  CANCELLED  DIVERTED  CRS_ELAPSED_TIME  \
0          -41.0        0.0        0.0       0.0             338.0   
1            4.0        0.0        0.0       0.0             110.0   
2          -33.0        0.0        0.0       0.0             335.0   
3           10.0        0.0        0.0       0.0             196.0   
4            8.0        0.0        0.0       0.0             247.0   
...          ...        ...        ...       ...               ...   
11226      -35.0        0.0        0.0       0.0             138.0   
11227       14.0        0.0        0.0       0.0             201.0   
11228      -16.0        0.0        0.0       0.0             311.0   
11229       -5.0        0.0        0.0       0.0             336.0   
11230      -12.0        0.0        0.0       0.0             120.0   

       ACTUAL_ELAPSED_TIME  DISTANCE  Unnamed: 25  
0                    295.0    2182.0          NaN  
1                    115.0     528.0          NaN  
2                    300.0    2182.0          NaN  
3                    205.0    1399.0          NaN  
4                    259.0    1927.0          NaN  
...                    ...       ...          ...  
11226                105.0     594.0          NaN  
11227                181.0    1399.0          NaN  
11228                295.0    1927.0          NaN  
11229                332.0    2182.0          NaN  
11230                110.0     594.0          NaN  

[11231 rows x 26 columns]

In [4]:
dataset.isnull().any()

YEAR                   False
QUARTER                False
MONTH                  False
DAY_OF_MONTH           False
DAY_OF_WEEK            False
UNIQUE_CARRIER         False
TAIL_NUM               False
FL_NUM                 False
ORIGIN_AIRPORT_ID      False
ORIGIN                 False
DEST_AIRPORT_ID        False
DEST                   False
CRS_DEP_TIME           False
DEP_TIME                True
DEP_DELAY               True
DEP_DEL15               True
CRS_ARR_TIME           False
ARR_TIME                True
ARR_DELAY               True
ARR_DEL15               True
CANCELLED              False
DIVERTED               False
CRS_ELAPSED_TIME       False
ACTUAL_ELAPSED_TIME     True
DISTANCE               False
Unnamed: 25             True
dtype: bool

In [5]:
dataset['ARR_DEL15'].value_counts()

0.0    9668
1.0    1375
Name: ARR_DEL15, dtype: int64

In [6]:
dataset.corr()

YEAR   QUARTER     MONTH  DAY_OF_MONTH  DAY_OF_WEEK  \
YEAR                  NaN       NaN       NaN           NaN          NaN   
QUARTER               NaN  1.000000  0.969890      0.003686     0.002389   
MONTH                 NaN  0.969890  1.000000      0.003095    -0.005027   
DAY_OF_MONTH          NaN  0.003686  0.003095      1.000000     0.010415   
DAY_OF_WEEK           NaN  0.002389 -0.005027      0.010415     1.000000   
FL_NUM                NaN -0.068411 -0.066573     -0.001812    -0.004133   
ORIGIN_AIRPORT_ID     NaN  0.021397  0.019809      0.000266     0.014915   
DEST_AIRPORT_ID       NaN  0.013962  0.012399      0.011000    -0.005374   
CRS_DEP_TIME          NaN  0.023468  0.021989      0.009126     0.005299   
DEP_TIME              NaN  0.024760  0.022717      0.007515     0.003021   
DEP_DELAY             NaN  0.015815  0.014460     -0.020573    -0.003005   
DEP_DEL15             NaN  0.013980  0.017456      0.011060    -0.000849   
CRS_ARR_TIME          NaN  0.028561  0.028657      0.000857     0.012490   
ARR_TIME              NaN  0.019311  0.019168     -0.001956     0.003068   
ARR_DELAY             NaN  0.017094  0.018201     -0.022221    -0.005965   
ARR_DEL15             NaN  0.023102  0.030161     -0.000597    -0.012063   
CANCELLED             NaN -0.025305 -0.035670     -0.013670    -0.011337   
DIVERTED              NaN -0.012403 -0.009693     -0.014101    -0.013820   
CRS_ELAPSED_TIME      NaN  0.028688  0.026254      0.002928     0.012862   
ACTUAL_ELAPSED_TIME   NaN  0.031273  0.030195      0.000175     0.012206   
DISTANCE              NaN  0.030841  0.028921      0.000320     0.017456   
Unnamed: 25           NaN       NaN       NaN           NaN          NaN   

                       FL_NUM  ORIGIN_AIRPORT_ID  DEST_AIRPORT_ID  \
YEAR                      NaN                NaN              NaN   
QUARTER             -0.068411           0.021397         0.013962   
MONTH               -0.066573           0.019809         0.012399   
DAY_OF_MONTH        -0.001812           0.000266         0.011000   
DAY_OF_WEEK         -0.004133           0.014915        -0.005374   
FL_NUM               1.000000           0.091777         0.051733   
ORIGIN_AIRPORT_ID    0.091777           1.000000        -0.240899   
DEST_AIRPORT_ID      0.051733          -0.240899         1.000000   
CRS_DEP_TIME        -0.036180          -0.197410         0.074794   
DEP_TIME            -0.043164          -0.200172         0.075888   
DEP_DELAY           -0.017794          -0.008670        -0.000673   
DEP_DEL15           -0.010673          -0.009245         0.019706   
CRS_ARR_TIME        -0.081598          -0.030674         0.032113   
ARR_TIME            -0.078940          -0.036143         0.027279   
ARR_DELAY           -0.011054          -0.018914         0.005625   
ARR_DEL15           -0.002378          -0.006250         0.029525   
CANCELLED           -0.027481          -0.001980        -0.000988   
DIVERTED            -0.008762           0.016843        -0.000462   
CRS_ELAPSED_TIME     0.058434           0.281852         0.476135   
ACTUAL_ELAPSED_TIME  0.060561           0.276192         0.482952   
DISTANCE             0.089529           0.395151         0.395802   
Unnamed: 25               NaN                NaN              NaN   

                     CRS_DEP_TIME  DEP_TIME  ...  CRS_ARR_TIME  ARR_TIME  \
YEAR                          NaN       NaN  ...           NaN       NaN   
QUARTER                  0.023468  0.024760  ...      0.028561  0.019311   
MONTH                    0.021989  0.022717  ...      0.028657  0.019168   
DAY_OF_MONTH             0.009126  0.007515  ...      0.000857 -0.001956   
DAY_OF_WEEK              0.005299  0.003021  ...      0.012490  0.003068   
FL_NUM                  -0.036180 -0.043164  ...     -0.081598 -0.078940   
ORIGIN_AIRPORT_ID       -0.197410 -0.200172  ...     -0.030674 -0.036143   
DEST_AIRPORT_ID          0.074794  0.075888  ...      0.032113  0.027279   


In [7]:
dataset['DEP_TIME'].fillna(dataset['DEP_TIME'].mean(),inplace = True)
dataset['DEP_DELAY'].fillna(dataset['DEP_DELAY'].mean(),inplace = True)
dataset['ARR_TIME'].fillna(dataset['ARR_TIME'].mean(),inplace = True)
dataset['ARR_DELAY'].fillna(dataset['ARR_DELAY'].mean(),inplace = True)
dataset['ARR_DEL15'].fillna(dataset['ARR_DEL15'].mode()[0],inplace = True)

In [8]:
dataset.isnull().any()

YEAR                   False
QUARTER                False
MONTH                  False
DAY_OF_MONTH           False
DAY_OF_WEEK            False
UNIQUE_CARRIER         False
TAIL_NUM               False
FL_NUM                 False
ORIGIN_AIRPORT_ID      False
ORIGIN                 False
DEST_AIRPORT_ID        False
DEST                   False
CRS_DEP_TIME           False
DEP_TIME               False
DEP_DELAY              False
DEP_DEL15               True
CRS_ARR_TIME           False
ARR_TIME               False
ARR_DELAY              False
ARR_DEL15              False
CANCELLED              False
DIVERTED               False
CRS_ELAPSED_TIME       False
ACTUAL_ELAPSED_TIME     True
DISTANCE               False
Unnamed: 25             True
dtype: bool

In [9]:
x = dataset[['DEP_TIME', 'DEP_DELAY', 'ARR_TIME', 'ARR_DELAY']]

In [10]:
x

DEP_TIME  DEP_DELAY  ARR_TIME  ARR_DELAY
0        1907.0        2.0    2102.0      -41.0
1        1344.0       -1.0    1439.0        4.0
2         942.0        2.0    1142.0      -33.0
3         820.0        1.0    1345.0       10.0
4        2256.0       -4.0     615.0        8.0
...         ...        ...       ...        ...
11226    1003.0       -2.0    1148.0      -35.0
11227    1559.0       34.0    2100.0       14.0
11228    1959.0        0.0    2154.0      -16.0
11229    1529.0       -1.0    1801.0       -5.0
11230     723.0       -2.0     913.0      -12.0

[11231 rows x 4 columns]

In [11]:
y = dataset[['ARR_DEL15']]

In [12]:
y

ARR_DEL15
0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
...          ...
11226        0.0
11227        0.0
11228        0.0
11229        0.0
11230        0.0

[11231 rows x 1 columns]

In [13]:
x = x.values
y = y.values

In [14]:
x, y

(array([[ 1.907e+03,  2.000e+00,  2.102e+03, -4.100e+01],
        [ 1.344e+03, -1.000e+00,  1.439e+03,  4.000e+00],
        [ 9.420e+02,  2.000e+00,  1.142e+03, -3.300e+01],
        ...,
        [ 1.959e+03,  0.000e+00,  2.154e+03, -1.600e+01],
        [ 1.529e+03, -1.000e+00,  1.801e+03, -5.000e+00],
        [ 7.230e+02, -2.000e+00,  9.130e+02, -1.200e+01]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]))

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)

In [17]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state = 0)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(random_state=0)

In [18]:
y_pred_dtc = dtc.predict(x_test)
y_pred_dtc

array([1., 0., 0., ..., 0., 0., 1.])

In [19]:
x_test_1 = np.array([[1521, 1, 2048, 16]])
x_test_1 =ss.fit_transform(x_test_1)
y_predict_1 = dtc.predict(x_test_1)
y_predict_1

array([0.])

In [20]:
x_test_2 = np.array([[1654, 29, 1909, 24]])

In [21]:
x_test_2 =ss.fit_transform(x_test_2)

In [22]:
y_predict_2 = dtc.predict(x_test_2)

In [23]:
y_predict_2

array([0.])

In [24]:
y_test

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [25]:
from sklearn.metrics import accuracy_score
acc_dtc = accuracy_score(y_test, y_pred_dtc)
acc_dtc

0.9839786381842457

In [26]:
from joblib import dump
dump(ss,'transform.save')

['transform.save']

In [27]:
from sklearn.metrics import confusion_matrix
cm_dtc = confusion_matrix(y_test, y_pred_dtc)
cm_dtc

array([[1973,    0],
       [  36,  238]], dtype=int64)

In [28]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [29]:
y_pred_lr = lr.predict(x_test)
y_pred_lr

array([1., 0., 0., ..., 0., 0., 1.])

In [30]:
acc_lr = accuracy_score(y_test, y_pred_lr)
acc_lr

0.9808633733867379

In [31]:
cm_lr =confusion_matrix(y_test, y_pred_lr)
cm_lr

array([[1973,    0],
       [  43,  231]], dtype=int64)

In [32]:
from joblib import dump
dump(lr,'lr.save')

['lr.save']